'use strict';
const meta=window.SCHEDULE_META, courses=meta.courses;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dateObj=s=>new Date(s+'T12:00:00Z');
const iso=d=>d.toISOString().slice(0,10);
const shift=(s,n)=>{let d=dateObj(s);d.setUTCDate(d.getUTCDate()+n);return iso(d)};
const fmt=(s,options={month:'short',day:'numeric'})=>new Intl.DateTimeFormat('en-CA',{...options,timeZone:'UTC'}).format(dateObj(s));
const timeFmt=t=>{if(!t)return 'Time not posted';let [h,m]=t.split(':').map(Number);return `${h%12||12}${m?':'+String(m).padStart(2,'0'):''} ${h>=12?'pm':'am'}`};
const state={view:'upcoming',active:new Set(Object.keys(courses)),nmm:'',range:'',team:'',mode:'month',anchor:today(),sessions:true};
let events=[];
const groupOpen={'Today':true,'Tomorrow':true,'Next 7 days':true,'Later this term':false};
document.addEventListener('toggle',ev=>{if(ev.target.matches?.('details[data-date-group]'))groupOpen[ev.target.dataset.dateGroup]=ev.target.open},true);
function parseCSV(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(Boolean))rows.push(row);let heads=rows.shift().map(s=>s.replace(/^\uFEFF/,''));return rows.map(r=>Object.fromEntries(heads.map((h,i)=>[h,r[i]||''])))}
function visible(e){return state.active.has(e.course)&&(!e.section||e.section===state.nmm)&&(!e.group||e.group===state.team)}
function sort(a,b){return (a.date+(a.time||'24:00')).localeCompare(b.date+(b.time||'24:00'))||a.course.localeCompare(b.course)}
function scheduleEvents(){return events.filter(e=>e.date&&visible(e)).sort(sort)}
function timeLabel(e){return e.time?timeFmt(e.time)+(e.end?'–'+timeFmt(e.end):''): 'Time not posted'}
function detail(e){return `<div class="event-body"><p>${esc(e.notes||'Additional instructions have not been supplied.')}</p><p class="detail-meta">${esc(e.category)} · ${esc(e.status)}${((e.course==='2225'&&['Quiz','Assessment'].includes(e.category))||(e.course==='2202'&&e.category==='Quiz'))?' · Tutorial window':''}${e.group?' · Team '+esc(e.group):''}${e.section?' · Tutorial '+esc(e.section):''}</p><p class="detail-meta">Source: ${esc(e.source)}</p>${e.grace?`<p class="grace"><strong>Grace period & assignment policy</strong><br>${esc(e.grace)}</p>`:''}</div>`}
function row(e,pending=false){const c=courses[e.course];return `<details class="event" style="--course:${c.color}"><summary>${pending?'':`<span class="event-date">${esc(fmt(e.date,{day:'numeric',month:'short'}))}</span>`}<span class="event-course">${esc(c.code)}</span><span class="event-title">${esc(e.title)}${(e.status!=='Confirmed'||(e.course==='2225'&&['Quiz','Assessment'].includes(e.category))||(e.course==='2202'&&e.category==='Quiz'))?`<small>${esc(e.status)}${((e.course==='2225'&&['Quiz','Assessment'].includes(e.category))||(e.course==='2202'&&e.category==='Quiz'))?' · Tutorial window':''}${e.group?' · Team '+esc(e.group):''}</small>`:''}</span><span class="event-time">${pending?esc(e.status):esc(timeLabel(e))}</span><span class="chevron" aria-hidden="true"></span></summary>${detail(e)}</details>`}
function helper(){let notes=[];if(state.active.has('nmm')&&!state.nmm)notes.push('Choose your NMM tutorial to include your quiz dates.');if(state.active.has('2220')&&!state.team)notes.push('Choose your structural group and team to include your lab and report dates.');return notes.length?`<p class="notice">${notes.map(esc).join(' ')}</p>`:''}
function recurring(){return `<details class="fold"><summary>Weekly requirements</summary><div class="fold-content">${Object.entries(courses).filter(([id,c])=>state.active.has(id)&&c.weekly).map(([id,c])=>`<article style="--course:${c.color}"><h3>${c.code}</h3><p>${esc(c.weekly)}</p></article>`).join('')||'<p>No courses selected.</p>'}</div></details>`}
function pending(){const list=events.filter(e=>!e.date&&visible(e));return `<details class="fold"><summary>Dates to confirm <span class="muted">(${list.length})</span></summary><div class="fold-content pending-list">${list.map(e=>row(e,true)).join('')||'<p>No pending dates for the selected courses.</p>'}</div></details>`}
function nextDiscussion(){if(!state.active.has('writing'))return null;let d=today();while(dateObj(d).getUTCDay()!==0)d=shift(d,1);if(d<'2026-09-20'||d>'2026-12-06'||d==='2026-10-11'||d==='2026-10-18')return null;return {id:'writing-next',course:'writing',title:'Discussion posts · check this week’s prompt',date:d,time:'23:59',end:'',category:'Participation',status:'Weekly rule',notes:'At least two posts on two separate days: one new thread and one reply. Weekly forums close Sunday at 11:59 pm. Check your tutorial OWL site to confirm an active prompt. Participation totals 10%.',source:'WRITING 2130F outline; next Sunday calculated from the weekly rule'}}
function upcoming(){let t=today(),items=scheduleEvents();let discussion=nextDiscussion();if(discussion)items.push(discussion);items.sort(sort);const nowTime=new Intl.DateTimeFormat('en-GB',{timeZone:'America/Toronto',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date());const current=items.filter(e=>e.date>t||e.date===t&&(!e.time||(e.end||e.time)>=nowTime));const groups=[['Today',e=>e.date===t],['Tomorrow',e=>e.date===shift(t,1)],['Next 7 days',e=>e.date>shift(t,1)&&e.date<=shift(t,7)],['Later this term',e=>e.date>shift(t,7)]];return `<div class="view-heading"><h2>Upcoming</h2><span>All times Eastern</span></div>${helper()}${groups.map(([name,filter])=>{let group=current.filter(filter);return group.length?`<details class="date-group" data-date-group="${name}" ${groupOpen[name]?'open':''}><summary><h3>${name}</h3><span class="group-count">${group.length} ${group.length===1?'item':'items'}</span><span class="chevron" aria-hidden="true"></span></summary>${group.map(e=>row(e)).join('')}</details>`:''}).join('')||'<p class="empty">No upcoming dated items for the selected courses. Check weekly requirements and dates to confirm below.</p>'}${recurring()}${pending()}<details class="fold"><summary>Past dates</summary><div class="fold-content">${items.filter(e=>!current.includes(e)).map(e=>row(e)).join('')||'<p class="muted">No past dates for the selected courses.</p>'}</div></details>`}
function sessionEvents(start,end){let out=[];for(let d=start;d<=end;d=shift(d,1)){if(d<'2026-09-16'||d>'2026-12-09'||d>='2026-10-10'&&d<='2026-10-18'||d==='2026-09-30')continue;let day=dateObj(d).getUTCDay();if(day===3&&state.active.has('2202')){if(events.some(e=>e.course==='2202'&&e.date===d&&e.category==='Quiz'))continue;out.push({id:'session-'+d,course:'2202',title:'Mandatory tutorial',date:d,time:'14:30',end:'17:30',category:'Tutorial',status:'Recurring schedule',notes:'SEB 1059. Attendance mandatory per course outline; weekly Part A work during tutorial. Individual submission deadlines not provided.',source:'CEE 2202A course outline and welcome announcement'})}}return out}
function calendar(){let d=dateObj(state.anchor),start,end,label;if(state.mode==='month'){start=iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1,12)));end=iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0,12)));label=fmt(start,{month:'long',year:'numeric'})}else{start=shift(state.anchor,-((d.getUTCDay()+6)%7));end=shift(start,6);label=fmt(start)+' – '+fmt(end,{month:'short',day:'numeric',year:'numeric'})}let shown=scheduleEvents();let disc=nextDiscussion();if(disc)shown.push(disc);if(state.sessions)shown.push(...sessionEvents(start,end));shown.sort(sort);let controls=`<div class="view-heading"><h2>Calendar</h2><span>All times Eastern</span></div>${helper()}<div class="toolbar"><span class="period">${esc(label)}</span><button id="previous" aria-label="Previous ${state.mode}">Previous</button><button id="today">Today</button><button id="next" aria-label="Next ${state.mode}">Next</button><button data-mode="month" aria-pressed="${state.mode==='month'}">Month</button><button data-mode="week" aria-pressed="${state.mode==='week'}">Week</button></div><label class="calendar-options"><input type="checkbox" id="sessions" ${state.sessions?'checked':''}> Include recurring mandatory tutorials</label>`;let body='';if(state.mode==='month'){const first=shift(start,-((dateObj(start).getUTCDay()+6)%7));const last=shift(end,6-((dateObj(end).getUTCDay()+6)%7));body='<p class="mobile-month-tip">Swipe the calendar sideways, or switch to Week for a compact agenda.</p><div class="calendar-scroll" tabindex="0" aria-label="Monthly calendar; scroll horizontally on small screens"><div class="calendar-grid">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(w=>`<div class="weekday">${w}</div>`).join('');for(let date=first;date<=last;date=shift(date,1)){let dayEvents=shown.filter(e=>e.date===date);body+=`<div class="day ${date.slice(0,7)!==start.slice(0,7)?'outside':''} ${date===today()?'today':''}"><span class="day-number">${Number(date.slice(8))}</span>${dayEvents.map(e=>`<button class="calendar-event" style="--course:${courses[e.course].color}" data-event="${e.id}"><span>${courses[e.course].code}</span>${esc(e.title)}<small>${e.time?' · '+esc(timeFmt(e.time)):''}</small></button>`).join('')}</div>`}body+='</div></div>'}else{for(let date=start;date<=end;date=shift(date,1)){let list=shown.filter(e=>e.date===date);body+=`<section class="week-day"><h3>${esc(fmt(date,{weekday:'long',month:'short',day:'numeric'}))}</h3>${list.map(e=>row(e)).join('')||'<p class="muted">Nothing scheduled.</p>'}</section>`}}window.currentCalendarEvents=shown;return controls+body+pending()}
function office(){return `<div class="view-heading"><h2>Office hours</h2><span>All times Eastern</span></div>${Object.entries(courses).filter(([id,c])=>state.active.has(id)&&c.office).map(([id,c])=>`<article class="office-item" style="--course:${c.color}"><h3>${c.code}<small>${esc(c.name)}</small></h3><p>${esc(c.office)}</p></article>`).join('')||'<p class="empty">Select a course to see office hours.</p>'}`}
function render(){ document.querySelectorAll('details[data-date-group]').forEach(el=>{groupOpen[el.dataset.dateGroup]=el.open}); $('#content').innerHTML=state.view==='upcoming'?upcoming():state.view==='calendar'?calendar():office();document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});}
function modal(e){$('#dialog-content').innerHTML=`<div style="color:${courses[e.course].color}">${courses[e.course].code}</div><h2>${esc(e.title)}</h2><p>${e.date?esc(fmt(e.date,{weekday:'long',month:'long',day:'numeric',year:'numeric'}))+' · '+esc(timeLabel(e)):esc(e.status)}</p>${detail(e)}`;$('#event-dialog').showModal()}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.view){state.view=b.dataset.view;render()}if(b.dataset.course){let c=b.dataset.course;state.active.has(c)?state.active.delete(c):state.active.add(c);b.setAttribute('aria-pressed',state.active.has(c));render()}if(b.id==='all-courses'){state.active=new Set(Object.keys(courses));document.querySelectorAll('[data-course]').forEach(x=>x.setAttribute('aria-pressed','true'));render()}if(b.dataset.mode){state.mode=b.dataset.mode;render()}if(['previous','next'].includes(b.id)){let step=b.id==='next'?1:-1;if(state.mode==='week')state.anchor=shift(state.anchor,7*step);else{let d=dateObj(state.anchor);state.anchor=iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+step,1,12)))}render()}if(b.id==='today'){state.anchor=today();render()}if(b.dataset.event){const e=window.currentCalendarEvents.find(x=>x.id===b.dataset.event);if(e)modal(e)}});
document.addEventListener('change',ev=>{const el=ev.target;if(el.id==='nmm'){state.nmm=el.value;render()}if(el.id==='structural'){state.range=el.value;state.team='';$('#team-label').hidden=!el.value;let lo=el.value==='19-36'?19:1,hi=el.value==='19-36'?36:18;$('#team').innerHTML='<option value="">Select team</option>'+Array.from({length:hi-lo+1},(_,i)=>`<option value="${i+lo}">Team ${i+lo}</option>`).join('');render()}if(el.id==='team'){state.team=el.value;render()}if(el.id==='sessions'){state.sessions=el.checked;render()}});
$('#updated').textContent='Last updated '+fmt(meta.updated,{month:'short',day:'numeric',year:'numeric'});
$('#course-filters').innerHTML=Object.entries(courses).map(([id,c])=>`<button class="course-toggle" data-course="${id}" aria-pressed="true" title="${esc(c.name)}" style="--course:${c.color}">${c.code}</button>`).join('');
$('#nmm').innerHTML+='<option value="" disabled>Find your TUT section in Student Center</option>'+Object.entries(meta.nmmSections).map(([s,[day,time,end,room]])=>`<option value="${s}">${s} · ${day.slice(0,3)} ${timeFmt(time)} · ${room}</option>`).join('');
fetch('schedule.csv',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Schedule download failed');return r.text()}).then(t=>{events=parseCSV(t);if(!events.length||events.some(e=>!courses[e.course]||!e.id||e.date&&!/^2026-\d{2}-\d{2}$/.test(e.date)))throw Error('Invalid schedule data');render()}).catch(()=>{$('#content').innerHTML='<p class="empty">The schedule could not load. Please refresh the page. If this is a downloaded copy, open it through a local web server or GitHub Pages.</p>'});
// Refresh date grouping after midnight or returning to the page; no personal data is stored.
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&events.length)render()});
setInterval(()=>{if(events.length&&!$('#event-dialog').open&&!document.querySelector('.event[open]'))render()},60000);
